import boto3

boto3.setup_default_session(
    aws_access_key_id='ASIA2MNVMGWN3NKZURHK',
    aws_secret_access_key='7cnvMupiUMlpwyfamCnnluGn7V97QnY2bICwWImM',
    aws_session_token='IQoJb3JpZ2luX2VjEKP//////////wEaCXVzLWVhc3QtMSJHMEUCIQDLNWg1HGUybGRs+Uzl8AcNQ9ZfuB6vqUMKZnhy6RheUQIgLLLwSx8OPCrMBDOGnMNzFhNzA8UcuomgBL+QWYEDWMsqmwMIGxAAGgw3MTM4ODE4MjY3MTUiDKYK0dgkv9KTbst5sCr4AssQDUE+VXfXzdm7EWceduokielSjWInakUBIBhcQwlNZrUkg6fShBIV7MUDHpuy1crDZQZaVjTJVpaMZ6mwpZz12JWIuOOZWm4VpA2IYXVScCHfoqcsZu8gA6DyxG7cGXGHDVWamIouNMywRQca3BEpjllyAao8YbMXKnn50l+y67ol9BIYuThI6FUdCxSI8HMRgqmy5yO2GRRJUDMw8F8jCrp/IetWRVELVMyFt02/NkATr8h9blawuDSZQaTmk9i7tZnBnztoyzzwQJ733QWIA5C40TAVoh1X41rbPLr39f9wbbC6G4XQM5MlEE1+9a2KVadqC5a72PxF5Q5u1icXerW01GFjiK1uJbTTE7mLXty2rhw9VGV9GpPtLkKKtJX4XP2SEgIhIhQj7vDCwml1dTbl1MPoFFZkH+7zGJ7bzvJm1n6OudGpA/hKUpqmmEaOiM4y4l7VYHhyVQgvJ+HQpLk4w7mJR0O1xYpWjlQXi7ZYVPLgVnYw3OH0uAY6pgFP0ag33crsih+izF3Y2GPifgTHXQWgCPtmDnUaYSSAGoiScXLRDGeqtMMCunoNgX6rTfoZM8cpILfOLVQmsf1bkNbVSMVZDrMrIcBbD70xGga5cbL6ZmlxAMKtRoxmT1XN00OrDoIZxL3Dp286bpiw2hIASzsSWXMkoQyV4mpLuZKD5YqIo7JhY/9RnhxVHKhM7QSz0zjZ5ytk0gfIGCCv46TRHWTm')

# criar um cliente
s3 = boto3.resource('s3')
# nome do bucket
nome_bucket = 'sprint5weber'
# criando bucket
s3.create_bucket(Bucket=nome_bucket)
arquivo = 'dados.csv'

# Nome do arquivo no bucket
nome_arquivo = 'dados.csv'

# fazer upaload para o bucket
s3.Bucket(nome_bucket).upload_file(arquivo, nome_arquivo)

print(f'Arquivo{nome_arquivo}\
    enviando para backet {nome_bucket} com sucesso!')
