# Use uma imagem base do Python
FROM python:3.12

# Defina o diretório de trabalho dentro do container
WORKDIR /etapa1

# Copie o arquivo carguru.py para o diretório de trabalho
COPY carguru.py .

# Execute o script Python quando o container iniciar
CMD ["python", "carguru.py"]
