# Use uma imagem base do Python
FROM python:3.12

# Defina o diretório de trabalho dentro do container
WORKDIR /etapa2

# Copie o script Python para o diretório de trabalho
COPY hash_generator.py .

# Execute o script Python quando o container iniciar
CMD ["python", "hash_generator.py"]
